/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author vldmrk
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    public JLabel getjLabelUlogovani() {
        return jLabelUlogovani;
    }

    public JLabel getjLabelAdminID() {
        return jLabelAdminID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelUlogovani = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUcesce = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabelAdminID = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAnsamblDodaj = new javax.swing.JMenuItem();
        jMenuItemAnsamblPrikaz = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemClanDodaj = new javax.swing.JMenuItem();
        jMenuItemClanPrikaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Korisnik:");

        jLabelUlogovani.setText("Nepoznat");

        jTableUcesce.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUcesce);

        jLabel2.setText("ID:");

        jLabelAdminID.setText("0");

        jMenu1.setText("Ansambli");

        jMenuItemAnsamblDodaj.setText("Dodaj");
        jMenuItemAnsamblDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnsamblDodajActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAnsamblDodaj);

        jMenuItemAnsamblPrikaz.setText("Prikazi");
        jMenuItemAnsamblPrikaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnsamblPrikazActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAnsamblPrikaz);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clanovi Drustva");

        jMenuItemClanDodaj.setText("Dodaj");
        jMenuItemClanDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClanDodajActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemClanDodaj);

        jMenuItemClanPrikaz.setText("Prikazi");
        jMenuItemClanPrikaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClanPrikazActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemClanPrikaz);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelAdminID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUlogovani))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAnsamblPrikazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnsamblPrikazActionPerformed
        coordinator.Coordinator.getInstanca().otvoriPrikazAnsamblFormu();
    }//GEN-LAST:event_jMenuItemAnsamblPrikazActionPerformed

    private void jMenuItemAnsamblDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnsamblDodajActionPerformed
        coordinator.Coordinator.getInstanca().otvoriDodajAnsamblFormu();
    }//GEN-LAST:event_jMenuItemAnsamblDodajActionPerformed

    private void jMenuItemClanPrikazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClanPrikazActionPerformed
        coordinator.Coordinator.getInstanca().otvoriPrikazClanFormu();
    }//GEN-LAST:event_jMenuItemClanPrikazActionPerformed

    private void jMenuItemClanDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClanDodajActionPerformed
        coordinator.Coordinator.getInstanca().otvoriDodajClanFormu();
    }//GEN-LAST:event_jMenuItemClanDodajActionPerformed

    public JTable getjTableUcesce() {
        return jTableUcesce;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAdminID;
    private javax.swing.JLabel jLabelUlogovani;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAnsamblDodaj;
    private javax.swing.JMenuItem jMenuItemAnsamblPrikaz;
    private javax.swing.JMenuItem jMenuItemClanDodaj;
    private javax.swing.JMenuItem jMenuItemClanPrikaz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUcesce;
    // End of variables declaration//GEN-END:variables
}
